# Generated by Django 2.0.6 on 2018-08-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20180824_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebilling_items',
            name='batchno',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicebilling_items',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.Company'),
        ),
        migrations.AddField(
            model_name='servicebilling_items',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebilling_items',
            name='sales_invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ERP.Salesinvoice'),
        ),
        migrations.AddField(
            model_name='servicebilling_items',
            name='service_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ERP.Item'),
        ),
        migrations.AddField(
            model_name='servicebilling_items',
            name='service_item_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicebilling_items',
            name='service_item_for',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ERP.Item'),
        ),
        migrations.AddField(
            model_name='servicebilling_items',
            name='service_item_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicebilling_items',
            name='warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.WareHouse'),
        ),
    ]
