# Generated by Django 2.0.6 on 2018-09-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_auto_20180920_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='max_credit_amount',
            field=models.IntegerField(default=0),
        ),
    ]
