# Generated by Django 2.1.1 on 2018-09-27 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_auto_20180927_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='ERP.Company'),
        ),
    ]
