# Generated by Django 2.1.1 on 2018-09-27 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_auto_20180927_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expensecategory_Created_By_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expensecategory_Modified_By_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
