# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0012_auto_20180927_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadno', models.CharField(max_length=200, unique=True)),
                ('lead_type', models.CharField(max_length=200)),
                ('lead_source', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Company')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='ERP.Customer')),
                ('contact_person_contact_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='ERP.Customer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='ERP.Customer')),
            ],
        ),
    ]
