# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0013_leadcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Item')),
            ],
        ),
        migrations.AddField(
            model_name='leadcs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadcs',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadcs',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='leadid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Leadcs'),
        ),
    ]
