# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0014_auto_20181013_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=True),
        ),
    ]
