# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0016_auto_20181017_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='leadid',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
