# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0018_enquirycrm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirycrm',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='enquirycrm',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='enquirycrm',
            name='modified_date',
        ),
    ]
