# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0021_auto_20181023_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquirycs',
            new_name='Enquiry',
        ),
    ]
