# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0025_auto_20181023_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=True, null=True),
        ),
    ]
