# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0028_auto_20181023_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
