# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0034_auto_20181023_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 22, 17, 40, 751243)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 22, 17, 40, 751262)),
        ),
        migrations.AlterField(
            model_name='leadcs',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 22, 17, 40, 750545)),
        ),
        migrations.AlterField(
            model_name='leadcs',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 22, 17, 40, 750566)),
        ),
    ]
