# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0035_auto_20181023_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 19, 26, 605202)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 19, 26, 605221)),
        ),
        migrations.AlterField(
            model_name='leadcs',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 19, 26, 604520)),
        ),
        migrations.AlterField(
            model_name='leadcs',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 19, 26, 604543)),
        ),
    ]
