# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0036_auto_20181024_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leadcs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leadcs',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
